### PR TITLE
Permit build with 2.3.0 librdkafka. Fixes #104

### LINKED ISSUE #104: Updating librdkafka (2.2.0 to 2.3.0) can present build error
Building against 2.3.0 on intel mac 

```
In file included from kfk.c:6:
/usr/local/include/librdkafka/rdkafka.h:8205:1: error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]
const int rd_kafka_TopicPartitionInfo_partition(
^~~~~~
1 error generated.
```

No such error when building against 2.2.0

### PR DESCRIPTION
**Pull request by sshanks-kx**
Tested with linux/osx. Now builds/runs with change.

### CODE REVIEW

**Review by awilson-kx — APPROVED** [review]
Looks good
